CREATE TABLE USER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(32) NOT NULL,
  AMOUNT NUMERIC(65, 2) NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;