CREATE TABLE STOCK (
  ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(32) NOT NULL DEFAULT '' COMMENT '名称',
  STOCK_NUM INT(8) NOT NULL COMMENT '库存',
  SALE_NUM INT(8) NOT NULL COMMENT '已售',
  VERSION INT(11) NOT NULL COMMENT '乐观锁，版本号',
  PRIMARY KEY(ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE STOCK_ORDER (
  ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  STOCK_ID BIGINT(20) UNSIGNED NOT NULL COMMENT 'STOCK_ID',
  USER_ID BIGINT(20) UNSIGNED NOT NULL,
  BUY_NUM INT(8) UNSIGNED NOT NULL COMMENT '购买数量',
  CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY(ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;